### ISSUE TITLE
yoloV8__obb

### ISSUE THREAD

**Issue by AlanjinWHU** [Koldim2001/YOLO-Patch-Based-Inference#14]
Can this patch be used for YOLOv8_obb rotation box detection? Why do I get the following error when performing inference with a rotation box detection model:
  41 pred = predictions[0]
     43 # Get the bounding boxes and convert them to a list of lists
---> 44 self.detected_xyxy = pred.boxes.xyxy.cpu().int().tolist()
     46 # Get the classes and convert them to a list
     47 self.detected_cls = pred.boxes.cls.cpu().int().tolist()

AttributeError: 'NoneType' object has no attribute 'xyxy'
Could you please explain?Thank you very much.

**Comment by Koldim2001** [comment]
You get such an error because currently rotated box models are not supported in the repository. Perhaps one day we will add them too

**Comment by AlanjinWHU** [comment]
Thank you very much for your response. Looking forward to the repository's update!
