### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by zhYao07** [Koldim2001/YOLO-Patch-Based-Inference#19]
When I change the model_path to the path of my trained YOLOv9 weights, it gives the following error:
Fusing layers... 
yolov9-t summary: 658 layers, 2618510 parameters, 0 gradients, 10.7 GFLOPs
Traceback (most recent call last):
  File "D:\Py_projects\yolov9-main\test_patch.py", line 8, in <module>
    element_crops = MakeCropsDetectThem(
  File "D:\Anaconda\envs\YOLOV9\lib\site-packages\patched_yolo_infer\nodes\MakeCropsDetectThem.py", line 113, in __init__
    self._detect_objects()
  File "D:\Anaconda\envs\YOLOV9\lib\site-packages\patched_yolo_infer\nodes\MakeCropsDetectThem.py", line 213, in _detect_objects
    crop.calculate_inference(
  File "D:\Anaconda\envs\YOLOV9\lib\site-packages\patched_yolo_infer\elements\CropElement.py", line 39, in calculate_inference
    predictions = model.predict(self.crop, imgsz=imgsz, conf=conf, iou=iou, classes=classes_list, verbose=False, **extra_args)
  File "D:\Anaconda\envs\YOLOV9\lib\site-packages\ultralytics\engine\model.py", line 563, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "D:\Anaconda\envs\YOLOV9\lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "D:\Anaconda\envs\YOLOV9\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "D:\Anaconda\envs\YOLOV9\lib\site-packages\ultralytics\engine\predictor.py", line 261, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "D:\Anaconda\envs\YOLOV9\lib\site-packages\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
  File "D:\Anaconda\envs\YOLOV9\lib\site-packages\ultralytics\utils\ops.py", line 219, in non_max_suppression
    if prediction.shape[-1] == 6:  # end-to-end model (BNC, i.e. 1,300,6)
AttributeError: 'list' object has no attribute 'shape'

How could I solve it?

**Comment by Koldim2001** [comment]
Good day. I will be happy to help you. can you please provide the code of how you initialize the model and feed it to the input of the patch inference + tell me your version of pytorh and the type of operating system

**Comment by zhYao07** [comment]
> Good day. I will be happy to help you. can you please provide the code of how you initialize the model and feed it to the input of the patch inference + tell me your version of pytorh and the type of operating system

Good day. Thank you for your assistance. Here is the code I use to initialize the model and feed it to the input of the patch inference:

`import cv2
from patched_yolo_infer import MakeCropsDetectThem, CombineDetections

# Load the image
img_path = "test.png"
img = cv2.imread(img_path)

element_crops = MakeCropsDetectThem(
    image=img,
    model_path="best.pt",
    segment=False,
    shape_x=640,
    shape_y=640,
    overlap_x=50,
    overlap_y=50,
    conf=0.5,
    iou=0.7,
)
result = CombineDetections(element_crops, nms_threshold=0.25)

# Final Results:
img=result.image
confidences=result.filtered_confidences
boxes=result.filtered_boxes
polygons=result.filtered_polygons
classes_ids=result.filtered_classes_id
classes_names=result.filtered_classes_names`

The best.pt file is the weights file I obtained by training my own dataset using YOLOv9. I am using PyTorch version 1.12.0+cu113
 and my operating system is windows11

**Comment by Koldim2001** [comment]
Yes, everything is correct in the code, perhaps the reason is the lack of some dependencies. I advise you to update PyTorch to version 2.3.1 and, just in case, update the ultralytics package to the latest one.

```pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121```

```pip install ultralytics==8.2.73```

---
PS:
It seems you are experiencing issues with running the code for network inference.
Please check if basic inference works in this environment:
```python
from ultralytics import YOLO
import cv2

img_path = "test.png"
img = cv2.imread(img_path)

model = YOLO("best.pt")
result = model.predict(img, conf=0.5, iou=0.7)
````

**Comment by zhYao07** [comment]
> patched_yolo_infer



> Yes, everything is correct in the code, perhaps the reason is the lack of some dependencies. I advise you to update PyTorch to version 2.3.1 and, just in case, update the ultralytics package to the latest one.
> 
> `pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121`
> 
> `pip install ultralytics==8.2.73`
> 
> PS: It seems you are experiencing issues with running the code for network inference. Please check if basic inference works in this environment:
> 
> ```python
> from ultralytics import YOLO
> import cv2
> 
> img_path = "test.png"
> img = cv2.imread(img_path)
> 
> model = YOLO("best.pt")
> result = model.predict(img, conf=0.5, iou=0.7)
> ```

Thank you very much. I think I've identified the issue. When I use the official weight files, everything works fine, but I encounter errors when using the weights I've trained. The problem might be that my training didn't properly match the model architecture.
