### ISSUE TITLE
Any workflow for slicing a training dataset ?

### ISSUE THREAD

**Issue by ClemSc** [Koldim2001/YOLO-Patch-Based-Inference#20]
Hello,

I am interested in this project =) 
I have previously used SAHI, which features an option to slice the annotated images dataset before training. Is there a similar feature in this project ? Or it it currently only for inferences ?

Cheers,
Clem

**Comment by Koldim2001** [comment]
At the moment, the library has the capability to generate a dataset of cropped patch images, but there is no ability to produce the same generation of the labeling itself.

That is, there is an option to input an image into the function, specify the patching parameters, and receive N saved patch images as output. Below, I will provide a description of the function itself:

### function __get_crops__:


    Preprocessing of the image. Generating crops with overlapping.

    Args:
        image_full (array): numpy array of a BGR image.
        shape_x (int): size of the crop in the x-coordinate.
        shape_y (int): size of the crop in the y-coordinate.
        overlap_x (float, optional): Percentage of overlap along the x-axis
            (how much subsequent crops borrow information from previous ones). Default is 15.
        overlap_y (float, optional): Percentage of overlap along the y-axis
            (how much subsequent crops borrow information from previous ones). Default is 15.
        show (bool): enables the mode to display images using plt.imshow. Default is False.
        save_crops (bool): enables saving generated images. Default is False.
        save_folder (str): folder path to save the images. Default is "crops_folder".
        start_name (str): starting name for saved images. Default is "image".
        resize (bool): If True, the image is resized to fit the last crop exactly.
                       If False, the image is not resized. Default is False.

    Returns:
        data_all_crops (list): List containing cropped images.

```python
import cv2
from patched_yolo_infer import get_crops

img_path = '/content/image-test.jpg'
image = cv2.imread(img_path)

data_all_crops = get_crops(
    image,
    shape_x=800,
    shape_y=500,
    overlap_x=50,
    overlap_y=10,
    show=False,
    save_crops=True,
    start_name="img",
    resize=True,
)
```

**Comment by ClemSc** [comment]
Ok, thank you for the prompt answer !
