### ISSUE TITLE
questions regarding rt-detr

### ISSUE THREAD

**Issue by idra79haza** [Koldim2001/YOLO-Patch-Based-Inference#21]
thank you for the great work!

I have questions regarding the RT-DETR model.

it seems the classes labels are not my custom trained, rather basic coco labels.

when I run on YOLOv8, it works fine, but when it comes to RT-DETR, it doesn't.

is there any ways that I can check?

**Comment by Koldim2001** [comment]
Can you please give an example of how you run the code when working with the RT-DETR model?

When working with RT-DETR, you need to load the model separately and then transfer it to inference. 

PS: there is an example of how to work with this model in the colab notebook

**Comment by idra79haza** [comment]
Got it! thank you for the quick support!!
