### ISSUE TITLE
Huggingface Model

### ISSUE THREAD

**Issue by TheMattBin** [Koldim2001/YOLO-Patch-Based-Inference#26]
Thanks for the great work! I would like to know if I can use this for model trained from Huggingface, such as RT-DETR but not from ultralytics?

**Comment by Koldim2001** [comment]
Good day. Unfortunately, at the moment we only have integration with ultralytics. Perhaps we will expand the list of models someday

**Comment by TheMattBin** [comment]
Got it, thanks for the quick response!
