### ISSUE TITLE
It ran wrong when the shape_x and shape_y are set larger than the image size

### ISSUE THREAD

**Issue by ZYJIQVV** [Koldim2001/YOLO-Patch-Based-Inference#27]
Hello,
I have a dataset containing images of different sizes from 640*640 to 4000*4000. My model produces the best results when taking images whose size is around 1024*1024. So I use YOLO Patch, this project to crop the images. But it ran wrong when the shape_x and shape_y = 1024 and the size of the image to be cropped is 640*640, and the error is as below:
`
Traceback (most recent call last):
  File "/data/D/zyj/code/YOLO-Patch-Based-Inference/predict.py", line 21, in <module>
    result = CombineDetections(element_crops, nms_threshold=0.25)
  File "/data/D/zyj/code/YOLO-Patch-Based-Inference/patched_yolo_infer/nodes/CombineDetections.py", line 99, in __init__
    self.image = element_crops.crops[0].source_image
IndexError: list index out of range
`
I think it is maybe because the crop size is larger than the image size.
Could you please teach me how to deal with this situation? Maybe the code could be modified so that when the crop size is larger than image size, the program will do nothing.

**Comment by Koldim2001** [comment]
If the patch size is larger than the size of your image, I recommend either running the inference directly through the classic YOLO inference without using the patch-based inference technology. Alternatively, you can process it as follows:
```
element_crops = MakeCropsDetectThem(
    image=img,
    model=model,
    shape_x=img.shape[1],
    shape_y=img.shape[0],
    overlap_x=0,
    overlap_y=0,
    ...
)
```

**Comment by ZYJIQVV** [comment]
> You correctly identified the issue. The algorithm only allows cropping patches that are smaller than the original image. Therefore, it's a good idea to add a check in the code to handle this scenario. Here's how you can implement this check:
> 
> ```python
> if patch_size_x > image.shape[1] or patch_size_y > image.shape[0]:
>      ...
> ```
> 
> Additionally, I recommend trying the technology for automatically determining patch sizes. You can find an example of this technology at the following link: [colab_example](https://colab.research.google.com/drive/1XCpIYLMFEmGSO0XCOkSD7CcD9SFHSJPA?usp=sharing#scrollTo=Wkt1FkAkhCwQ)

Thanks for your replies!
