### ISSUE TITLE
tensorRT support and video detection support

### ISSUE THREAD

**Issue by mohammdkaraca** [Koldim2001/YOLO-Patch-Based-Inference#6]
Hi, im very new to machine learning and computer vision I was wondering if your package supports tensorRt models since inference time is very important to me and also if you could provide a code example on how to use your package to detect objects in a video and then visuilize the results in a new output video thanks in advanced sorry for my english.

**Comment by Koldim2001** [comment]
Unfortunately, at the moment, only classic inference through ultralytics models is supported (pytorch), but there is such a wide variety of models that you can choose any with high inference speed (use nano size models for faster inference). However, the fewer patches you make in the patch-based inference we are developing, the faster your frame will be processed, but fewer objects can be detected. I wanted to clarify, what exactly are you interested in? Detection or instance segmentation?

**Comment by mohammdkaraca** [comment]
detection I need the speed to be at minimum 10 frames per second can your package support this speed? Im currently using a yolov8x.pt model but the tensor versions speed is 5-10 times the speed would it be possible for you to give me a code example to test your package on a video? with my pt model thanks again.

**Comment by Koldim2001** [comment]
@mohammdkaraca Yes, I understand your question. The classic YOLO can achieve around 30-50 fps depending on the chosen architecture and the hardware of the computer on which the calculations are performed. The library we are developing is designed to increase the number of detections by dividing the image into crops and running the crops sequentially. Thus, the more crops (patches) you want to generate, the slower the inference will be. Therefore, to roughly estimate, you should take the fps of a regular YOLO and divide it by the number of crops (this is a rough calculation of speed). If you want to perform calculations on video with parameters already selected by our algorithm, please provide the values so that it is easier for me to write code for your unique task. Please show the code for how you plan to perform inference on a single frame using our library. Thank you in advance.

**Comment by Koldim2001** [comment]
@mohammdkaraca Here's an example of how you can perform inference on a neural network using a library. If you specifically want to use a patch-based approach for inference rather than a classic one, please let me know and provide the desired parameters. In the example below, I implemented video processing and saving of the final frames. You can read the documentation on the function ```visualize_results_usual_yolo_inference``` to add some customization.

```python
import cv2
from ultralytics import YOLO
from patched_yolo_infer import visualize_results_usual_yolo_inference

# Load the YOLO model
model = YOLO("yolov8n.pt")

# Function to process a video file
def process_video(input_video_path, output_video_path, model):
    # Open the input video file
    cap = cv2.VideoCapture(input_video_path)

    # Get the video's frame width and height
    frame_width = int(cap.get(3))
    frame_height = int(cap.get(4))

    # Define the codec and create VideoWriter object
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_video_path, fourcc, 20.0, (frame_width, frame_height))

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Apply YOLO model to the frame
        result = visualize_results_usual_yolo_inference(
            frame,
            model,
            imgsz=640,
            conf=0.5,
            iou=0.7,
            delta_colors=3,
            thickness=2,
            font_scale=1.0,
            show_boxes=True,
            show_confidences=False,
            return_image_array=True
        )

        # Write the resulting frame to the output video
        out.write(result)

        # Display the resulting frame (optional)
        cv2.imshow('Processed Frame', result)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # Release everything when done
    cap.release()
    out.release()
    cv2.destroyAllWindows()

# Example usage
input_video_path = 'input.mp4'
output_video_path = 'output.mp4'
process_video(input_video_path, output_video_path, model)
```

**Comment by mohammdkaraca** [comment]
thanks alot at the moment this is even faster than I need im guessing that to change the patch inference parameters I need to l look at this
  result = visualize_results_usual_yolo_inference(
            frame,
            model,
            imgsz=640,
            conf=0.5,
            iou=0.7,
            delta_colors=3,
            thickness=2,
            font_scale=1.0,
            show_boxes=True,
            show_confidences=True,
            return_image_array=True
        )
but I didnt really understand it much my images are 1920 × 1080 If you could just explain each parameter and what it does. also since its faster than what I need right now if I raise the path inference sizes would I get better results? 

lastly, its possible to get the bbox of each detected object right? since I need it for something.
thanks in advanced you have been a huge help.

**Comment by Koldim2001** [comment]
@mohammdkaraca 
For the most part, this function allows you to flexibly configure the final visualization of the results of the neural network inference. I even have a video tutorial on YouTube on how to do it - https://www.youtube.com/watch?v=nBQuWa63188

Here is an explanation of all the input arguments of the function:

```
def visualize_results_usual_yolo_inference(
    img,
    model,
    imgsz=640,
    conf=0.5,
    iou=0.7,
    segment=False,
    show_boxes=True,
    show_class=True,
    fill_mask=False,
    alpha=0.3,
    color_class_background=(0, 0, 255),
    color_class_text=(255, 255, 255),
    thickness=4,
    font=cv2.FONT_HERSHEY_SIMPLEX,
    font_scale=1.5,
    delta_colors=0,
    dpi=150,
    random_object_colors=False,
    show_confidences=False,
    axis_off=True,
    show_classes_list=[],
    return_image_array=False
):
    """
    Visualizes the results of usual YOLOv8 or YOLOv8-seg inference on an image

    Args:
        img (numpy.ndarray): The input image in BGR format.
        model: The object detection or segmentation model (yolov8).
        imgsz (int): The input image size for the model. Default is 640.
        conf (float): The confidence threshold for detection. Default is 0.5.
        iou (float): The intersection over union threshold for detection. Default is 0.7.
        segment (bool): Whether to perform instance segmentation. Default is False.
        show_boxes (bool): Whether to show bounding boxes. Default is True.
        show_class (bool): Whether to show class labels. Default is True.
        fill_mask (bool): Whether to fill the segmented regions with color. Default is False.
        alpha (float): The transparency of filled masks. Default is 0.3.
        color_class_background (tuple): The background bgr color for class labels. Default is (0, 0, 255) (red).
        color_class_text (tuple): The text color for class labels. Default is (255, 255, 255) (white).
        thickness (int): The thickness of bounding box and text. Default is 4.
        font: The font type for class labels. Default is cv2.FONT_HERSHEY_SIMPLEX.
        font_scale (float): The scale factor for font size. Default is 1.5.
        delta_colors (int): The random seed offset for color variation. Default is 0.
        dpi (int): Final visualization size (plot is bigger when dpi is higher).
        random_object_colors (bool): If True, colors for each object are selected randomly.
        show_confidences (bool): If True and show_class=True, confidences near class are visualized.
        axis_off (bool): If True, axis is turned off in the final visualization.
        show_classes_list (list): If empty, visualize all classes. Otherwise, visualize only classes in the list.
        return_image_array (bool): If True, the function returns the image bgr array instead of displaying it. 
                                   Default is False.

    Returns:
        None/np.array
    """
```

**Comment by Koldim2001** [comment]
> ![glitch](https://private-user-images.githubusercontent.com/118883094/331982966-9cde5db1-8773-41cf-bad5-e5e817933481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTE5ODksIm5iZiI6MTcxNjE5MTY4OSwicGF0aCI6Ii8xMTg4ODMwOTQvMzMxOTgyOTY2LTljZGU1ZGIxLTg3NzMtNDFjZi1iYWQ1LWU1ZTgxNzkzMzQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNzU0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWFkMzI2ZmQ3MDUxOWVmMzU4NTEzYjNjZWEwZDVkN2JiMDkwZDllMzEyMTYwOGI1NTAwYjk4ZTZkN2U0ZGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GEpfkhC5Yg4LQgUW3-zFTAJNPt2L1BU-SwZrckToSB8)
> 
> its detecting some objects multiple times instead of once is this a normal behaviour?

Decrease iou parameter (iou=0.3). Does it help?

**Comment by Koldim2001** [comment]
@hanbangzou How are your results? Did it help your problem?

PS: All usage examples are provided in [Google Colab](https://colab.research.google.com/drive/1eM4o1e0AUQrS1mLDpcgK9HKInWEvnaMn?usp=sharing)

**Comment by Koldim2001** [comment]
@mohammdkaraca 

Important information: The latest update to the library has added the capability to input any converted ultralytics detection model into TensorRT, which further increases fps by another 1.5 times. 

```python
# Load the YOLOv8 model
model = YOLO("yolov8m.engine") 

visualize_results_usual_yolo_inference(
    frame,
    model,
    imgsz,
    conf,
    iou,
    segment=False,
    ...
)
```
