### ISSUE TITLE
set memory_optimize=False, can't dectect anything

### ISSUE THREAD

**Issue by LudovicoYIN** [Koldim2001/YOLO-Patch-Based-Inference#9]
When i set memory_optimize=False, i can't dectect anything

**Comment by Koldim2001** [comment]
@LudovicoYIN How are your results? Did using filtered_masks instead of filtered_polygons help you solve the problem?

**Comment by LudovicoYIN** [comment]
Thank you so much Sir, i forget add masks=result.filtered_masks, i still use filtered_polygons
